# Generated by Django 3.2.5 on 2021-07-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='djangoClasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=50)),
                ('Course_Number', models.IntegerField(default=0)),
                ('Instructor_name', models.CharField(default='', max_length=50)),
                ('Duration', models.FloatField(default=0)),
            ],
        ),
    ]
