# Generated by Django 2.1.5 on 2021-07-16 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=60)),
                ('Last_Name', models.CharField(max_length=60)),
                ('Email', models.CharField(max_length=70)),
                ('UserName', models.CharField(max_length=20)),
            ],
        ),
    ]
