# Generated by Django 2.1.5 on 2021-07-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(choices=[('Ms.', 'Ms.'), ('non-binary', 'non-binary'), ('Mr.', 'Mr.')], max_length=60),
        ),
    ]
