# Generated by Django 2.1.5 on 2021-07-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210717_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('non-binary', 'non-binary')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='First_Name',
            field=models.CharField(max_length=60),
        ),
    ]
