# Generated by Django 2.1.5 on 2021-07-19 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20210717_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Prefix',
            field=models.CharField(choices=[('non-binary', 'non-binary'), ('Mr.', 'Mr.'), ('Ms.', 'Ms.')], max_length=20, null=True),
        ),
    ]
